name: "Go unittest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  unittest-check:
    name: unittest-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - run: |
        go test -v ./...



  frontend-build-check:
    name: frontend-build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build 
        uses: docker/build-push-action@v2
        with:
          file: ./frontend/Dockerfile
          context: ./frontend
          push: false
          tags: | 
            bidaya0/gbatect-frontend:latest
